#!/usr/bin/env python3
"""Regenerate assets/og-image-{lang}.png from template.html via headless Chrome.

Usage: python3 scripts/og-image/generate.py [lang ...]
       (no args = regenerate all languages)

Content per language is defined in CONTENT below. Edit it, then rerun.
"""
import io
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
ASSETS_DIR = REPO_ROOT / "assets"
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

CONTENT = {
    "es": dict(
        HEADLINE="Los primeros tres días los aguanta cualquiera.",
        SUBTEXT="Seguimiento de challenges mensuales para iPhone. Sin cuenta, sin tracking, sin anuncios.",
        TIME="12:18", TODAY="Hoy", DATE_LINE="dom. 12 jul · 3/4 hechos",
        QUOTE="«Cada día cumplido es una promesa que te haces.»",
        TASK1="Escribir en el diario", TASK1_COUNT="12/30",
        TASK2="Salir a correr", TASK2_COUNT="10/30",
        TASK3="Meditar 🔥", TASK3_COUNT="10/30",
        TASK4="Ahorrar", TASK4_COUNT="8/30",
        TAB1="Hoy", TAB2="Challenges", TAB3="Logros",
    ),
    "fr": dict(
        HEADLINE="Les trois premiers jours, tout le monde y arrive.",
        SUBTEXT="Suivi de challenges mensuels pour iPhone. Sans compte, sans tracking, sans pub.",
        TIME="12:18", TODAY="Aujourd’hui", DATE_LINE="dim. 12 juil. · 3/4 faits",
        QUOTE="« Chaque jour accompli est une promesse que tu te fais. »",
        TASK1="Écrire un journal", TASK1_COUNT="12/30",
        TASK2="Aller courir", TASK2_COUNT="10/30",
        TASK3="Méditer 🔥", TASK3_COUNT="10/30",
        TASK4="Économiser", TASK4_COUNT="8/30",
        TAB1="Aujourd’hui", TAB2="Challenges", TAB3="Succès",
    ),
    # DE/EN reference images predate this script and weren't generated by it;
    # add entries here only if they need to be regenerated from scratch.
}


def render(lang: str, data: dict) -> None:
    template = (SCRIPT_DIR / "template.html").read_text(encoding="utf-8")
    for key, value in data.items():
        template = template.replace("{{" + key + "}}", value)

    html_path = SCRIPT_DIR / f"_render-{lang}.html"
    html_path.write_text(template, encoding="utf-8")

    out_path = ASSETS_DIR / f"og-image-{lang}.png"
    subprocess.run(
        [
            CHROME, "--headless", "--disable-gpu", "--hide-scrollbars",
            "--window-size=1200,630",
            f"--screenshot={out_path}",
            f"file://{html_path}",
        ],
        check=True,
        capture_output=True,
    )
    html_path.unlink()
    print(f"{lang}: wrote {out_path}")


def main() -> None:
    langs = sys.argv[1:] or list(CONTENT)
    for lang in langs:
        if lang not in CONTENT:
            print(f"no content defined for '{lang}', skipping", file=sys.stderr)
            continue
        render(lang, CONTENT[lang])


if __name__ == "__main__":
    main()
